### ISSUE TITLE
[Package Request] - php-pecl-imagick

### ISSUE THREAD

**Issue by sunaoka** [amazonlinux/amazon-linux-2022#207]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

php-pecl-imagick

**Is this an update to existing package or new package request?**

New package request.

**Is this package available in Amazon Linux 2?**

Yes.

**Number of users impacted**

More than 1 million users we serve.

**Comment by rbpltr** [comment]
I've been getting around this by using:

```
dnf install -y gcc make ImageMagick-devel php-{devel,pear}
pecl channel-update pecl.php.net
pear config-set php_ini /etc/php.ini
yes '' | pecl install imagick
```

I'm hoping for a cleaner, more robust way!

**Comment by singhpaul** [comment]
+1. We'd also like to see this package included.

**Comment by chrisking** [comment]
+1 for this being useful. Also given it was in earlier php releases it makes sense to add it as part of the standard bundle that rolls out with new version support.

**Comment by felder** [comment]
Just noting that I'd love to see this package added for AL2023 and PHP 8.2 (and future versions of php).  We've added the necessary commands to get pecl to install imagick, but it'd be a lot nicer to have a repo package for it.

**Comment by iandrewt** [comment]
php-pecl-imagick is available in EPEL9, can we get it added to SPAL too? https://dl.fedoraproject.org/pub/epel/9/Everything/aarch64/Packages/p/php-pecl-imagick-3.7.0-1.el9.aarch64.rpm

**Comment by danbrellis** [comment]
For anyone using Elastic Beanstalk, you can add the install script into a [commands config](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands) in ebextensions:

```yaml
# /.ebextensions/dependencies.config
packages:
  yum:
    ImageMagick: []
    ImageMagick-devel: []
commands: # Download and install imagick
  01-channels:
    command: "pecl update-channels"
  02-download:
    command: "pecl download Imagick"
  03-mkdir:
    command: "if [ ! -d imagicksrc ] ; then mkdir -p imagicksrc; fi"
  04-tar:
    command: "tar -xf imagick*.tgz -C imagicksrc --strip-components 1"
  05-clean:
    command: "rm -f imagick*.tgz"
  06-phpize:
    command: "phpize"
    cwd: /imagicksrc
  07-config:
    command: "./configure"
    cwd: /imagicksrc
  08-make:
    command: "make"
    cwd: /imagicksrc
  09-install:
    command: "make install"
    cwd: /imagicksrc
```

And then ensure the module is enabled in your custom php.ini:
```yaml
# /.ebextensions/php.config
files:
  "/etc/php.d/99custom.ini":
    mode: "000644"
    owner: root
    group: root
    content: |
      extension = imagick.so
    encoding: plain
```
